### ISSUE TITLE
PSI4 density option permitted, but does nothing

### ISSUE THREAD

**Issue by takenbymood** [qubekit/QUBEKit#144]
The code for "density" calculations in the psi4 engine is currently commented out. The program does not throw any error until it can't find the expected .wfx file output from the density step during the charges step.

```
Calculating bonds and angles with modified Seminario method... Bond and angle parameters calculated
Performing density calculation with psi4... Density calculation complete
Chargemol calculating charges using DDEC3...

An exception occurred with: Execute.run
Exception: [Errno 2] No such file or directory: '/data/QUBEKit_ethane2_2020_09_07_ethane_example/06_density/ethane2.wfx'
```

It would be great to be able to use PSI4 for density calculations (g09 licenses etc etc), but if that's not an option right now it would still be nice if the program threw some error a little earlier on.

Really enjoying testing this package out!

**Comment by CRingrose94** [comment]
Unfortunately there is currently no way of automatically generating a box of the correct size for the density stage with PSI4. We have experimented with adding a method which fits a box around the molecule but it was too temperamental and ultimately better disabled.

I'll add an error message which triggers at the beginning of the run to show this. Thanks

**Comment by ankur9511** [comment]
(I am just a user of QUBEkit)
There could be a way to save psi density as fchk file, then use multiwfn/gmultiwfn to create /cube/.cub file, and then use that as input in chargemol that is compatible with .cube/.cub file.

**Comment by jthorton** [comment]
@ankur9511 This is definitely something we want to look at in future, either the pathway you describe or trying to create a wfx/wfn object from the wavefunction in psi4 and using this with chargemol. 

For now, Psi4 can directly perform [MBIS](https://doi.org/10.1021/acs.jctc.6b00456) charge partitioning and we have recently fit a QUBEKit model to work with this which you can read about [here](https://chemrxiv.org/engage/chemrxiv/article-details/61c0d3a31e13eb80bb0010ec). Hopefully, this should allow you to use Psi4 to derive force fields with QUBEKit. 

To use the MBIS workflow described in the paper (with the latest version of QUBEKit on conda-forge 2.1.1) simply run `qubekit run --sm CCC -n propane -p 3b | 5e` where `3b` & `5e` are the two protocols we have fit a QUBEKit model for, more details on the models can be found in the pre-print I linked. Please let me know if you are able to test this out or if you have any issues with QUBEKit!
