### ISSUE TITLE
Missing v-site test cases

### ISSUE THREAD

**Issue by CRingrose94** [qubekit/QUBEKit#256]
Need to add test cases for (non-)symmetric sites with all variations of site vectors. 

Currently testing only covers halogens; needs to also cover alcohols (symmetric and non-symmetric), amines, etc.

Once MBIS is implemented, testing should be much easier just using PSI4, rather than all the Chargemol output files.

**Comment by jthorton** [comment]
Added amine special case tests which include a 4-point site in #350  also included water tip4p tests.
