### ISSUE TITLE
RdKit _CIPError Keyerror

### ISSUE THREAD

**Issue by Ajaykhanna** [qubekit/QUBEKit#301]
Hi, I'm trying to parameterize two molecules "NBD" & "Methoxy Coumarin" in their ground state but I keep landing on this error:
`"""
Traceback (most recent call last):
  File "/home/akhanna2/anaconda3/envs/qubekit_2022/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/akhanna2/qubekit/ndb_nh2/qubekit_2022/qubekit/qubekit/engines/geometry_optimiser.py", line 155, in optimise
    result_mol = self._handle_output(molecule=molecule, opt_output=opt_result)
  File "/home/akhanna2/qubekit/ndb_nh2/qubekit_2022/qubekit/qubekit/engines/geometry_optimiser.py", line 211, in _handle_output
    result_mol.to_file(file_name="opt.xyz")
  File "/home/akhanna2/qubekit/ndb_nh2/qubekit_2022/qubekit/qubekit/molecules/ligand.py", line 220, in to_file
    return RDKit.mol_to_file(rdkit_mol=self.to_rdkit(), file_name=file_name)
  File "/home/akhanna2/qubekit/ndb_nh2/qubekit_2022/qubekit/qubekit/molecules/ligand.py", line 927, in to_rdkit
    assert qb_atom.stereochemistry == rd_atom.GetProp(
KeyError: '_CIPCode'
"""
I tried googling the issue on RDKit GitHub and found this [workaround](https://github.com/openforcefield/openff-toolkit/issues/196):
"If R or S can't be achieved by trying CW/CCW, force-add them with rdatom.SetProp('_CIPCode', 'R')". I tried changing, rd_atom.GetProp -->  rdatom.GetProp('_CIPCode', 'R') but then there was C++ issue.

Click on this [link](https://ucmerced.box.com/s/q55ql8mvku3gfzf1bsw1yf7szlm8z35k) to get the PDB files and the configuration files. Could you please provide your feedback on this? Thank you

**Comment by Ajaykhanna** [comment]
Hi, Josh; thank you for providing your feedback. Using the SDF formatted file you have provided, the parameterization is working fine. I'm on step 09_torsion_scan, and I'll update you again once the parameterization is done. 

Yes, I tried working with smiles for this molecule, but when I try to run:
 "`qubekit run -sm COC1=CC2=C(C=C1)C(=CC(=O)O2)CC(=O)O -n methoxycoumarin`", I get into an error 
` -bash: syntax error near unexpected token (`
I thought maybe this could be a problem with this particular molecule, so I tried benzaldehyde
`qubekit run -sm C1=CC=C(C=C1)C=O -n benzaldehyde `but again landed on the same problem. 
So I tested these smile strings on [LigParGen ](http://zarbi.chem.yale.edu/ligpargen/) server to test if I was getting the right molecules. LigParGen server was able to convert these smile strings to the respective molecules. I think the brackets are not being parsed correctly, and that's why I started with a PDB file instead. 

Yes, I used a different QM method because the basis set was too big to work with, so I changed it to a smaller basis set. For the functional, I believe wB97x-D, B3LYP and Cam-B3LYP will provide similar results as we are currently interested in sample decent molecular configurations from a parameterized forcefield. But now you have mentioned that "Rfree parameters" could lead to different intermolecular interactions. I can test this with forcefield parameterized with both CAM-B3LYP and wB97x-D. Thank you for sharing the pre-print. I have been actively following QubeKit development. Your pre-print will be the discussion of our next group meeting. 

Again thank you for your instant feedback.

**Comment by jthorton** [comment]
That's good news that the run is now working! For the smiles issue, I think any smiles which contain brackets just need to be inside quotes so the input would become `qubekit run -sm 'COC1=CC2=C(C=C1)C(=CC(=O)O2)CC(=O)O' -n methoxycoumarin`  Ill make sure to update the documentation with more information about using this input.

**Comment by Ajaykhanna** [comment]
Yes, I just realized this. I was going through babel file format [commands](https://openbabel.org/docs/dev/Command-line_tools/babel.html), and I found out how to add work with smile strings with brackets. Yes, it works well now with the quotes around the smile string.
