### ISSUE TITLE
Final Parameters Combination Rules 

### ISSUE THREAD

**Issue by outburned** [qubekit/QUBEKit#328]
Hello,

I noticed that the combination rule used in the `final_parameters` output file in QUBEKit is in the Amber format. For instance, this is how it's written in `.xml` and `.gro` file format respectively. 
```
<NonbondedForce coulomb14scale="0.8333333333" lj14scale="0.5" combination="amber">
```
```
[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
1               2               no              1            0.83333333  
```
Is it possible to change the format of the combination rule to that of other force fields? 

I want to solvate this molecule with a given water model.

**Comment by jthorton** [comment]
Hi @outburned, the nonbonded and torsional parameters output by qubekit are now optimised to work with the Amber style combination rules and changing this will probably degrade the performance of the parameters so it is not advised to change them. If you really wanted to though you could manually change the comb-rule in the gromacs file, or if you wanted to run using openmm you would have to use a custom nonbonded force to implement a different rule like the example [here](http://zarbi.chem.yale.edu/ligpargen/openMM_tutorial.html) for simulating the OPLS force field.

**Comment by outburned** [comment]
Hi, thanks for the clarification!
