### ISSUE TITLE
Output XML file format

### ISSUE THREAD

**Issue by UnWaDo** [qubekit/QUBEKit#338]
Hello!

Before finding issue #328 I thought, that the resulting force field is in OpenMM format. However you noted in mentioned issue, that epsilon and sigma parameters can not be used in OpenMM directly

So what is the actual sense of parameters from `final_parameters`' `.xml` file? Do other parameters follow OpenMM notation? (it is important, _e.g._ for constant `k` in HarmonicBondForce, which may be already divided by 2 or not)

Do Amber combination rules refer to [this letter](http://archive.ambermd.org/200407/0050.html) and do `sigma` from ForceField mean the same as _r*_ from the letter?

Would be glad to get aid on this problem

**Comment by jthorton** [comment]
Hi @UnWaDo sorry for the confusion hopefully this helps!

> However you noted in mentioned issue, that epsilon and sigma parameters can not be used in OpenMM directly

The XML files in the `final_parameters` are in a valid OpenMM format and can be used directly without modification to simulate the parameterised molecule using the default AMBER functional form and combination rules, see [here](http://docs.openmm.org/6.2.0/userguide/theory.html#nonbondedforce) for more details and definitions of the parameters.  

To load the forcefield you can use the following in a script
```python
from openmm import app

force_field = app.ForceField("name_of_file.xml")
```

The user in issue #328 wanted to use non-AMBER combination rules. This causes an issue as the dihedral and non-bonded terms in QUBEKit have been optimised to work with AMBER (OpenMM default ) functional form so changing the rules will harm the performance of the force field.

**Comment by UnWaDo** [comment]
Thank you very much!

I used OpenMM's ForceField for my calculations, but then I saw that issue and was a little concerned if I was doing something wrong.
