### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by entropybit** [qubekit/QUBEKit#361]
Hi,

I am currently running qubekit on a 96 core node on our cluster. I am only trying it out with one molecule right now my run command was
```
qubekit run -sm "O=C1C(=C(O)C[C@@](O1)(C1CCCC1)CCc1cc(nc(c1)CC)CC)Cc1nn2c(n1)nc(cc2C)C" -n 3FRZ
```
I am using guassian/g16 for this as it was available on our cluster via the module system. 
I guess it is stil in the optimization phase as this output would suggest to me

```
  opt_result = qcng.compute_procedure(
/work/scratch/b_mayer/miniconda3/envs/qubekit/lib/python3.10/site-packages/qubekit/engines/geometry_optimiser.py:148: FutureWarning: Using the `local_options` keyword argument is depreciated in favor of using `task_config`, in version 0.30.0 it will stop working.
  opt_result = qcng.compute_procedure(
```

Now as far as I can see this only uses 4 cores of my available 96 cores which is an immense waste of computational power. So my question is: How can I make it use more cores, are there any flags for fine control of parallelization in qubekit ?

**Comment by jthorton** [comment]
Hi @entropybit,

by default qubekit is configured to use 4 cores and 10 GB of memory however this can be changed via the command line by adding `--cores 96 --memory xxx` to your command. I hope this helps!

**Comment by entropybit** [comment]
Oh sorry, yeah I didn't think of using --help with qubekit run.
